#!/usr/bin/env python3
"""Capture fresh Claude capabilities and verify scoped native worker evidence.

No controller mutations or hook-shaped fixture events are generated by this
program. Claude executes the workflow through the candidate's real hooks. A
separate, explicitly labelled capability probe tests harmless updatedInput use.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import signal
import stat
import subprocess
import sys
import tempfile
import time
import uuid

ROOT = Path(__file__).resolve().parents[1]
PHASES = ("product", "design", "plan", "build", "evaluate", "engineering", "retro")
LIMIT = 64 * 1024 * 1024
HOOK_ACTIONS = {"SessionStart": "context", "PreToolUse": "screen",
                "PostToolUse": "tool-observe", "SubagentStart": "subagent-start",
                "SubagentStop": "subagent-stop", "Stop": "session-verify",
                "UserPromptSubmit": "human-input"}


def stamp():
    return datetime.now(timezone.utc).isoformat()


def digest(data):
    return hashlib.sha256(data).hexdigest()


def read_regular(path, limit=LIMIT):
    path = Path(path).absolute()
    for part in (path, *path.parents):
        if part.is_symlink():
            raise ValueError(f"Refusing symlink: {part}")
    fd = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0))
    with os.fdopen(fd, "rb") as stream:
        if not stat.S_ISREG(os.fstat(stream.fileno()).st_mode):
            raise ValueError(f"Not a regular file: {path}")
        data = stream.read(limit + 1)
    if len(data) > limit:
        raise ValueError(f"Read budget exceeded: {path}")
    return data


def load(path):
    return json.loads(read_regular(path))


def save(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def fingerprint(root):
    files = [*sorted((root / "taskplane").glob("*.py")),
             root / "hooks/hooks.json", root / ".claude-plugin/plugin.json"]
    return {"root": str(root), "version": load(root / ".claude-plugin/plugin.json")["version"],
            "member_sha256": {str(p.relative_to(root)): digest(read_regular(p)) for p in files}}


def command(argv, cwd, env=None, timeout=30):
    try:
        result = subprocess.run(argv, cwd=cwd, env=env, text=True, capture_output=True, timeout=timeout)
        return {"argv": argv, "exit_code": result.returncode,
                "stdout": result.stdout, "stderr": result.stderr}
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"argv": argv, "exit_code": None, "error": str(exc)}


def clean_environment(workspace):
    # Child sessions must not inherit this Codex/Taskplane run's identity. Keep
    # the real HOME, auth and host configuration; do not create an auth bypass.
    env = {k: v for k, v in os.environ.items() if not k.startswith(("TASKPLANE_", "CODEX_"))
           and k not in {"CLAUDECODE", "CLAUDE_SESSION_ID", "CLAUDE_PLUGIN_ROOT", "PLUGIN_ROOT"}}
    env["TASKPLANE_WORKSPACE"] = str(workspace)
    return env


def hook_action(event, command):
    """Translate only the shipped hook wrapper; never interpret shell syntax."""
    action = HOOK_ACTIONS.get(event)
    expected = ('if [ -n "${CLAUDE_PLUGIN_ROOT:-${PLUGIN_ROOT:-}}" ]; then python3 '
                '"${CLAUDE_PLUGIN_ROOT:-${PLUGIN_ROOT}}/taskplane/tp.py" ' + str(action)
                + '; else echo \'{"decision":"block","reason":"Taskplane plugin root unavailable"}\'; exit 2; fi')
    if action is None or command != expected:
        raise ValueError(f"Unsupported hook command for {event}")
    return action


def proxy(config_path, index):
    """Only invoked by the host-configured hook; stdin is never manufactured."""
    config = load(config_path)
    raw = sys.stdin.buffer.read(1024 * 1024 + 1)
    if len(raw) > 1024 * 1024:
        print("Hook input exceeded capture bound", file=sys.stderr)
        return 2
    item = config["commands"][int(index)]
    action = hook_action(item["event"], item["command"])
    event = json.loads(raw)
    plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT") or os.environ.get("PLUGIN_ROOT")
    if not plugin_root:
        print('{"decision":"block","reason":"Taskplane plugin root unavailable"}')
        return 2
    root = Path(plugin_root)
    before = fingerprint(root)
    started = stamp()
    python = shutil.which("python3")
    if python is None:
        raise ValueError("Hook interpreter python3 unavailable")
    argv = [python, str(root / "taskplane/tp.py"), action]
    result = subprocess.run(argv, input=raw, capture_output=True)
    stdout = result.stdout
    probe = None
    if (config.get("probe") and item["event"] == "PreToolUse"
            and event.get("tool_name") == "Bash"
            and event.get("tool_input", {}).get("command") == config["probe"]["original"]
            and result.returncode == 0):
        try:
            response = json.loads(stdout) if stdout.strip() else {}
            specific = response.setdefault("hookSpecificOutput", {})
            if (response.get("decision") != "block" and specific.get("permissionDecision") != "deny"
                    and "updatedInput" not in specific):
                specific.update(hookEventName="PreToolUse", updatedInput={
                    **event["tool_input"], "command": config["probe"]["rewritten"]})
                stdout = json.dumps(response).encode() + b"\n"
                probe = "capability_fixture_only"
        except (ValueError, TypeError):
            pass  # Preserve original failure/unknown output, never override it.
    record = {"schema": "taskplane.claude-hook-capture/v1", "started_at": started,
              "ended_at": stamp(), "event": item["event"], "input": event,
              "delegate_command": item["command"], "delegate_argv": argv,
              "delegate_exit_code": result.returncode,
              "delegate_stdout": result.stdout.decode(errors="replace"),
              "delegate_stderr": result.stderr.decode(errors="replace"),
              "host_stdout": stdout.decode(errors="replace"), "capability_fixture": probe,
              "runtime": before, "runtime_unchanged": before == fingerprint(root)}
    save(Path(config["capture"]) / (uuid.uuid4().hex + ".json"), record)
    sys.stdout.buffer.write(stdout)
    sys.stderr.buffer.write(result.stderr)
    return result.returncode


def stage_plugin(candidate, folder, capture, probe):
    staged = folder / "plugin"
    staged.mkdir()
    # Use exactly the package surface, not the source checkout's state or tests.
    for name in (".claude-plugin", "hooks", "skills", "agents", "taskplane", "lenses", "docs", "workflows", "assets"):
        source = candidate / name
        if source.exists():
            if source.is_symlink():
                raise ValueError(f"Plugin directory is a symlink: {source}")
            shutil.copytree(source, staged / name, ignore=shutil.ignore_patterns("__pycache__", "tests"))
    for name in ("README.md", "LICENSE", "CHANGELOG.md", "PRIVACY.md", "TERMS.md"):
        if (candidate / name).exists():
            shutil.copyfile(candidate / name, staged / name)
    hooks = load(staged / "hooks/hooks.json")
    config = {"capture": str(capture), "probe": probe, "commands": []}
    config_path = folder / "proxy-config.json"
    harness_copy = folder / "capture.py"
    shutil.copyfile(Path(__file__), harness_copy)
    for event, groups in hooks["hooks"].items():
        for group in groups:
            for hook in group["hooks"]:
                if hook.get("type") != "command" or not isinstance(hook.get("command"), str):
                    raise ValueError("Instrumentation supports command hooks only")
                hook_action(event, hook["command"])
                index = len(config["commands"])
                config["commands"].append({"event": event, "command": hook["command"]})
                hook["command"] = shlex.join([sys.executable, str(harness_copy), "--hook-proxy", str(config_path), str(index)])
    save(config_path, config)
    save(staged / "hooks/hooks.json", hooks)
    return staged


def stream_rows(path, limit=LIMIT):
    rows, errors = [], []
    try:
        data = read_regular(path, limit)
    except (OSError, ValueError) as exc:
        return [], [str(exc)]
    for number, line in enumerate(data.splitlines(), 1):
        try:
            row = json.loads(line)
            if isinstance(row, dict):
                rows.append(row)
        except ValueError:
            errors.append(f"{path}:{number}: non-JSON record")
    return rows, errors


def objects(value):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from objects(child)
    elif isinstance(value, list):
        for child in value:
            yield from objects(child)


def transcript_evidence(captures, session):
    paths = set()
    for capture in captures:
        event = capture["input"]
        if event.get("session_id") == session:
            for key in ("transcript_path", "agent_transcript_path"):
                value = event.get(key)
                if isinstance(value, str) and value.endswith(".jsonl"):
                    paths.add(Path(value))
    # Derive only the selected session's exact child directory, never search
    # unrelated projects. Existing transcripts are read-only and never padded.
    for path in list(paths):
        if path.stem == session:
            directory = path.with_suffix("") / "subagents"
            if directory.is_dir() and not directory.is_symlink():
                paths.update(list(directory.glob("agent-*.jsonl"))[:32])
    schemas, tool_schemas, calls, results, records, sources, errors = [], [], [], [], [], [], []
    notifications = []
    remaining = LIMIT
    for path in sorted(paths):
        rows, failures = stream_rows(path, remaining)
        errors.extend(failures)
        if failures:
            continue
        data = read_regular(path, remaining)
        remaining -= len(data)
        sources.append({"path": str(path), "sha256": digest(data), "bytes": len(data)})
        records.extend(rows)
        for number, row in enumerate(rows, 1):
            attached = row.get("attachment", {})
            midturn = (row.get("type") == "attachment" and row.get("renderedRole") == "system"
                       and isinstance(attached, dict) and attached.get("type") == "queued_command"
                       and attached.get("commandMode") == "task-notification"
                       and attached.get("origin") == {"kind": "task-notification", "producer": "session-task"})
            if ((row.get("type") == "user" and row.get("promptSource") == "system"
                    and row.get("turnOrigin") == "task_notification"
                    and row.get("origin") == {"kind": "task-notification", "producer": "session-task"}
                    or midturn) and row.get("sessionId") == session):
                notifications.append({"path": str(path), "record": number, "event": row})
            for obj in objects(row):
                if isinstance(obj.get("name"), str) and obj["name"] in {
                        "SubagentHandback", "Task", "Agent", "TaskOutput", "TaskStop", "SendMessage"}:
                    schema = obj.get("input_schema", obj.get("inputSchema", obj.get("parameters")))
                    if isinstance(schema, dict):
                        item = {"name": obj["name"], "path": str(path), "record": number, "schema": schema,
                                "description": obj.get("description"), "object_sha256": digest(json.dumps(obj, sort_keys=True).encode())}
                        tool_schemas.append(item)
                        if obj["name"] == "SubagentHandback":
                            schemas.append(item)
                if obj.get("type") == "tool_use":
                    calls.append({"path": str(path), "record": number, "call": obj})
                elif obj.get("type") == "tool_result":
                    results.append({"path": str(path), "record": number, "result": obj})
    return {"sources": sources, "handback_schemas": schemas, "tool_schemas": tool_schemas,
            "completion_notifications": notifications,
            "calls": calls, "results": results, "errors": errors}, records


def capture_summary(captures, native, stream):
    pre = [x for x in captures if x["event"] == "PreToolUse"]
    post = [x for x in captures if x["event"] == "PostToolUse"]
    children = sorted({x["input"]["agent_id"] for x in captures if isinstance(x["input"].get("agent_id"), str)})
    rewrites = []
    for row in pre:
        try:
            reply = json.loads(row["host_stdout"])
        except ValueError:
            continue
        updated = reply.get("hookSpecificOutput", {}).get("updatedInput")
        if updated:
            event = row["input"]
            matched = [p for p in post if p["input"].get("tool_use_id") == event.get("tool_use_id")
                       and p["input"].get("agent_id") == event.get("agent_id")]
            representations = ["rewritten" if p["input"].get("tool_input") == updated else
                               "original" if p["input"].get("tool_input") == event.get("tool_input") else
                               "other_or_absent" for p in matched]
            marker = None
            if row["capability_fixture"]:
                import re
                token = re.search(r"CW_REWRITTEN_[0-9a-f]{32}", updated.get("command", ""))
                marker = token[0] if token else None
            applied = any(marker in json.dumps(p["input"].get("tool_response", {})) for p in matched) if marker else None
            rewrites.append({"call_id": event.get("tool_use_id"), "agent_id": event.get("agent_id"),
                             "fixture": row["capability_fixture"], "original": event.get("tool_input"),
                             "updated": updated, "post": [p["input"] for p in matched],
                             "post_input_representation": representations,
                             "fixture_rewritten_execution_observed": applied})
    handbacks = [r for r in captures if r["input"].get("tool_name") == "SubagentHandback"]
    return {"automatic_event_counts": {name: sum(r["event"] == name for r in captures) for name in sorted({r["event"] for r in captures})},
            "child_agent_ids": children, "rewrites": rewrites,
            "handback_events": handbacks, "handback_schema_status": "observed" if native["handback_schemas"] else "unknown",
            "handback_schemas": native["handback_schemas"],
            "terminal_events": [r["input"] for r in captures if r["event"] == "SubagentStop"],
            "loaded_plugins": [r.get("plugins") for r in stream if r.get("type") == "system" and r.get("subtype") == "init"],
            "runtime_roots": sorted({r["runtime"]["root"] for r in captures}),
            "runtime_changed_during_hook": any(not r["runtime_unchanged"] for r in captures)}


def live_permissions(plugin, workspace):
    """Normal per-session approvals for the disposable fixture, never bypass mode."""
    runtime = shlex.join([str(Path(sys.executable).resolve()), str(plugin / "taskplane/tp.py")])
    reports = load(workspace / ".taskplane/bootstrap/scope.json")["paths"]["engineering"]
    commands = ["pwd", "cd " + shlex.quote(str(workspace)),
                "python3 -c 'import time; time.sleep(60)'",
                "python3 -c 'raise SystemExit(17)'",
                "python3 -c 'from averages import average; print(average([]))'",
                "python3 -c 'from settings import listener_port; print(listener_port(\"70000\"))'",
                "cat " + shlex.quote(str(plugin / "skills/tp-go/references/shared-flow.md"))]
    permissions = [f"Bash({value})" for value in commands]
    permissions += [f"Bash({runtime} flow {action} *)" for action in
                    ("activate", "start", "context", "worker", "report", "prevalidate", "submit", "present")]
    # Claude filesystem rules use // for absolute paths; a single / anchors a
    # rule to the project root and would not authorize these fixture files.
    permissions += [f"Bash({runtime} graph *)", f"Read(/{plugin}/**)", f"Read(/{workspace}/**)"]
    permissions += [f"{tool}(/{workspace / path})" for path in reports for tool in ("Write", "Edit")]
    return permissions


def launch(claude, plugin, cwd, folder, prompt, timeout, model, workspace=None):
    session = str(uuid.uuid4())
    argv = [claude, "-p", "--output-format", "stream-json", "--verbose", "--include-hook-events",
            "--plugin-dir", str(plugin), "--session-id", session]
    if model:
        argv += ["--model", model]
    if workspace is not None:
        argv += ["--add-dir", str(plugin), str(workspace), "--allowedTools", *live_permissions(plugin, workspace)]
    (folder / "prompt.txt").write_text(prompt)
    started = stamp()
    timed_out = False
    with (folder / "stream.jsonl").open("wb") as out, (folder / "stderr.log").open("wb") as err:
        process = subprocess.Popen(argv, cwd=cwd, env=clean_environment(workspace or cwd), stdin=subprocess.PIPE,
                                   stdout=out, stderr=err, start_new_session=True)
        try:
            process.communicate(prompt.encode(), timeout=timeout)
        except subprocess.TimeoutExpired:
            timed_out = True
            # Termination is a harness timeout observation, not a worker success.
            os.killpg(process.pid, signal.SIGTERM)
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
                process.wait()
    return {"argv": argv, "session_id": session, "started_at": started, "ended_at": stamp(),
            "launch_cwd": str(cwd), "selected_workspace": str(workspace or cwd),
            "exit_code": process.returncode, "timed_out": timed_out,
            "process_exit": "observed", "worker_exit": "unknown" if timed_out else "requires_native_terminal_evidence"}


def capability_prompt(probe):
    return f"""Perform a bounded host capability inspection in this disposable project.
Use Bash to execute this exact harmless command once: {probe['original']}
Record the actual output. A local diagnostic hook may change this one command.
Use the exposed native Task or Agent tool to inspect sample.py for correctness and return a
concise real finding to its caller with SubagentHandback if that tool is available.
Launch the child in the background: set run_in_background=true only if the exposed
schema includes that parameter; otherwise use the current fork-mode schema unchanged.
The child must first Read sample.py and run the same harmless command once, then
invoke SubagentHandback using the exact currently exposed schema. Do not guess a
recipient field or use external messaging. If SubagentHandback is unavailable, the
child should return its ordinary final answer. Receive the real native child result
through the host's actual completion notification or TaskOutput, using its returned ID.
Report unavailable tools and failures exactly. Do not edit configuration, invoke
hook entrypoints, create workflow state, skip permissions, or invent successful
events. This capability inspection does not establish scoped worker recovery.
"""


def preflight(args):
    claude = shutil.which(args.claude) or str(Path(args.claude).expanduser())
    result = {"claude": claude, "candidate": fingerprint(args.plugin_dir)}
    result["version"] = command([claude, "--version"], ROOT)
    result["help"] = command([claude, "--help"], ROOT)
    result["auth"] = command([claude, "auth", "status"], ROOT)
    help_text = result["help"].get("stdout", "")
    result["required_flags"] = {flag: flag in help_text for flag in
                                ("--plugin-dir", "--output-format", "--verbose", "--include-hook-events", "--session-id")}
    result["status"] = "pass" if result["version"].get("exit_code") == 0 and all(result["required_flags"].values()) else "fail"
    result["auth_note"] = "Auth failure may reflect a sandbox keychain restriction; retry through the normal permitted host, never disable permissions."
    return result


def main():
    if len(sys.argv) == 4 and sys.argv[1] == "--hook-proxy":
        return proxy(sys.argv[2], sys.argv[3])
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--preflight", action="store_true", help="Inspect CLI and candidate without launching a model")
    mode.add_argument("--prepare", action="store_true", help="Create fixtures, then stop for independent host probe and supported workspace binding")
    mode.add_argument("--capabilities", action="store_true", help="Fresh automatic host capture; never E2E success")
    mode.add_argument("--live", action="store_true", help="Fresh scoped lifecycle verification")
    parser.add_argument("--plugin-dir", type=lambda v: Path(v).expanduser().resolve(),
                        help="Unpacked candidate or installed plugin directory; loaded through supported --plugin-dir")
    parser.add_argument("--claude", default=shutil.which("claude") or str(Path.home() / ".local/bin/claude"))
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--model", help="Optional explicitly selected Claude model")
    parser.add_argument("--prepare-kind", choices=("capabilities", "live"), default="capabilities")
    parser.add_argument("--prepared-dir", type=lambda v: Path(v).expanduser().resolve(),
                        help="Reuse a separately prepared and bound fixture; always starts fresh Claude sessions")
    args = parser.parse_args()
    explicit_candidate = args.plugin_dir is not None
    args.plugin_dir = args.plugin_dir or ROOT
    report = {"schema": "taskplane.claude-live-verification/v1", "created_at": stamp(),
              "mode": "prepare" if args.prepare else "preflight" if args.preflight else "capabilities" if args.capabilities else "live",
              "status": "unknown", "assurance": "cooperative automatic host observations; not protected-host attestation"}
    try:
        if args.output.exists():
            previous = read_regular(args.output)
            retained = Path(tempfile.mkdtemp(prefix="taskplane-claude-prior-")).resolve() / "report.json"
            retained.write_bytes(previous)
            report["previous_report"] = {"path": str(retained), "sha256": digest(previous)}
            prior = json.loads(previous)
            if prior.get("prepared_fixture_ref"):
                report["prepared_fixture_ref"] = prior["prepared_fixture_ref"]
        if args.live:
            reference = report.get("prepared_fixture_ref")
            if not args.prepared_dir and reference:
                body = read_regular(reference["path"])
                if digest(body) != reference["sha256"]:
                    raise ValueError("Recorded prepared-fixture reference changed")
                args.prepared_dir = Path(reference["path"]).parent
            if args.prepared_dir:
                manifest_path = args.prepared_dir / "prepared.json"
                manifest = load(manifest_path)
                report["prepared_fixture_ref"] = {"path": str(manifest_path), "sha256": digest(read_regular(manifest_path))}
                selected = Path(manifest["candidate"]["root"])
                if explicit_candidate and args.plugin_dir != selected:
                    raise ValueError("Explicit candidate differs from prepared candidate; prepare a fresh fixture")
                args.plugin_dir = selected
        report["preflight"] = preflight(args)
        if args.prepare:
            prepare_fixtures(args, report)
        elif args.preflight:
            report["status"] = report["preflight"]["status"]
        elif report["preflight"]["status"] != "pass":
            report["status"] = "fail"
        elif args.live:
            run_live(args, report)
        else:
            if not args.prepared_dir:
                raise ValueError("Run --prepare --prepare-kind capabilities, independently inspect/bind its workspace, then --capabilities --prepared-dir PATH")
            prepared = args.prepared_dir
            workspace, plugin = prepared / "project", prepared / "plugin"
            if not (workspace / ".taskplane/workspace-binding.json").is_file():
                raise ValueError("Prepared workspace needs the supported independent probe/bind step before live capture")
            config_path = prepared / "proxy-config.json"
            config = load(config_path)
            probe = config.get("probe")
            if not probe:
                raise ValueError("Prepared fixture is not a capability fixture")
            folder = prepared / ("attempt-" + uuid.uuid4().hex)
            folder.mkdir()
            capture = folder / "hooks"
            capture.mkdir()
            config["capture"] = str(capture)
            save(config_path, config)
            report.update(evidence_directory=str(folder), staged_candidate=fingerprint(plugin),
                          instrumentation={"kind": "delegating hook capture", "changed_members": ["hooks/hooks.json"],
                                           "updated_input_probe": "capability fixture only; excluded from live lifecycle checks"})
            report["process"] = launch(args.claude, plugin, workspace, folder, capability_prompt(probe), args.timeout, args.model)
            captures = [load(p) for p in capture.glob("*.json")]
            stream, errors = stream_rows(folder / "stream.jsonl")
            native, _ = transcript_evidence(captures, report["process"]["session_id"])
            report["observations"] = capture_summary(captures, native, stream)
            report["native_transcripts"] = native
            report["capture_errors"] = errors
            report["status"] = "observed" if captures and report["process"]["exit_code"] == 0 else "fail"
            report["e2e_status"] = "not_evaluated"
    except (OSError, ValueError, KeyError, TypeError) as exc:
        report.update(status="fail", error=f"{type(exc).__name__}: {exc}")
        if args.output.exists() and "previous_report" not in report:
            print(json.dumps({"status": "fail", "error": report["error"],
                              "previous_report_preserved_at": str(args.output.resolve())}), file=sys.stderr)
            return 1
    save(args.output, report)
    print(json.dumps({"status": report["status"], "output": str(args.output.resolve()),
                      "evidence_directory": report.get("evidence_directory"), "error": report.get("error")}))
    return 0 if report["status"] in {"pass", "observed", "prepared"} else 1


EXTRA_REVIEWS = (
    ('C', 'bounds.py', 'lower-bound',
     '"""Clamp a reading to the inclusive lower and upper bounds."""\ndef clamp(value, low, high):\n    return min(value, high)\n',
     'from bounds import clamp; print(clamp(-5, 0, 10))'),
    ('D', 'extensions.py', 'filename-parsing',
     '"""Return the final filename extension."""\ndef extension(name):\n    return name.split(".")[1]\n',
     'from extensions import extension; print(extension("archive.tar.gz"))'),
    ('E', 'prices.py', 'percentage-arithmetic',
     '"""Subtract a percentage discount from the price."""\ndef discounted(price, percent):\n    return price * (1 - percent)\n',
     'from prices import discounted; print(discounted(100, 20))'),
    ('F', 'distinct.py', 'duplicate-handling',
     '"""Count distinct input values."""\ndef count_unique(values):\n    return len(values)\n',
     'from distinct import count_unique; print(count_unique([1, 1, 2]))'),
    ('G', 'flags.py', 'boolean-parsing',
     '"""Parse the strings true and false as boolean values."""\ndef parse_flag(value):\n    return bool(value)\n',
     'from flags import parse_flag; print(parse_flag("false"))'),
    ('H', 'maximum.py', 'negative-values',
     '"""Return the largest element of a nonempty sequence."""\ndef largest(values):\n    result = 0\n    for value in values:\n        result = max(result, value)\n    return result\n',
     'from maximum import largest; print(largest([-7, -2]))'),
    ('I', 'events.py', 'event-ordering',
     '"""Return the latest item from a nonempty oldest-first event list."""\ndef latest(events):\n    return events[0]\n',
     'from events import latest; print(latest(["old", "new"]))'),
    ('J', 'chunks.py', 'trailing-data',
     '"""Split all values into chunks, retaining a final partial chunk."""\ndef chunks(values, size):\n    return [values[i:i+size] for i in range(0, len(values)-size+1, size)]\n',
     'from chunks import chunks; print(chunks([1, 2, 3], 2))'),
)


def make_project(folder, worktree, worker_count=2):
    if worker_count not in (2, 10):
        raise ValueError('The prepared review fixture supports two or ten workers')
    original = folder / "original-project"
    original.mkdir()
    (original / "averages.py").write_text(
        '"""Average sensor observations."""\n\n'
        'def average(values):\n    return sum(values) / len(values)\n')
    (original / "settings.py").write_text(
        '"""Parse the HTTP listener configuration."""\n\n'
        'def listener_port(value):\n    return int(value)\n')
    extra = EXTRA_REVIEWS if worker_count == 10 else ()
    for _, source, _, body, _ in extra:
        (original / source).write_text(body)
    sources = ['averages.py', 'settings.py', *[row[1] for row in extra]]
    commands = [["git", "init", "-q"], ["git", "add", *sources],
                ["git", "-c", "user.name=Claude worker validation", "-c", "user.email=validation@example.invalid",
                 "commit", "-qm", "Disposable review inputs"]]
    evidence = []
    for argv in commands:
        result = command(argv, original)
        evidence.append(result)
        if result.get("exit_code") != 0:
            raise ValueError(f"Disposable Git fixture setup failed: {result}")
    workspace = original
    if worktree:
        workspace = folder / "execution-worktree"
        result = command(["git", "worktree", "add", "--detach", str(workspace), "HEAD"], original)
        evidence.append(result)
        if result.get("exit_code") != 0:
            raise ValueError(f"Disposable worktree setup failed: {result}")
    bootstrap = workspace / ".taskplane/bootstrap"
    bootstrap.mkdir(parents=True)
    tasks = []
    cases = [("A", "averages.py", "correctness"), ("B", "settings.py", "input-validation")]
    cases.extend((suffix, source, lens) for suffix, source, lens, _, _ in extra)
    for suffix, source, lens in cases:
        tasks.append({"id": "CW-LIVE-" + suffix, "phase": "engineering", "dependencies": [],
                      "execution": "native_required", "owner": "native-worker", "review_lens": lens,
                      "paths": [f".taskplane/review-{suffix.lower()}.md", f".taskplane/failure-{suffix.lower()}.md"],
                      "read_inputs": [source], "criteria": ["REVIEW-" + suffix],
                      "purpose": f"Independently review {source}, reproduce a concrete boundary defect and report source locations.",
                      "context_budget_bytes": 65536,
                      "verification": "Reproduce a real defect, cite source and expected behavior, write the scoped review and hand it back."})
    paths = [".taskplane/review.json", ".taskplane/review.md", ".taskplane/review-checks.json"]
    paths += [p for task in tasks for p in task["paths"]]
    scope = {"execution_contract": "native-default/v1", "criteria": ['REVIEW-' + row[0] for row in cases],
             "paths": {phase: paths if phase == "engineering" else [] for phase in PHASES},
             "verification_inputs": sources}
    save(bootstrap / "scope.json", scope)
    save(bootstrap / "tasks.json", {"tasks": tasks})
    return original, workspace, evidence


def prepare_fixtures(args, report):
    if args.prepared_dir:
        raise ValueError("--prepare creates a new fixture; use --prepared-dir only with --capabilities or --live")
    folder = Path(tempfile.mkdtemp(prefix="taskplane-claude-" + args.prepare_kind + "-")).resolve()
    fixtures = []
    if args.prepare_kind == "capabilities":
        workspace, capture = folder / "project", folder / "hooks"
        workspace.mkdir()
        capture.mkdir()
        (workspace / "sample.py").write_text("def average(values):\n    return sum(values) / len(values)\n")
        nonce = uuid.uuid4().hex
        probe = {"original": f"printf 'CW_ORIGINAL_{nonce}\\n'", "rewritten": f"printf 'CW_REWRITTEN_{nonce}\\n'"}
        plugin = stage_plugin(args.plugin_dir, folder, capture, probe)
        fixtures.append({"name": "capabilities", "directory": str(folder), "workspace": str(workspace),
                         "original_project": str(workspace), "plugin": str(plugin), "probe_file": "sample.py"})
    else:
        for name, worktree, retry in (("concurrent", False, False), ("worktree-failure-retry", True, True)):
            scenario_dir = folder / name
            scenario_dir.mkdir()
            capture = scenario_dir / "hooks"
            capture.mkdir()
            plugin = stage_plugin(args.plugin_dir, scenario_dir, capture, None)
            original, workspace, git = make_project(scenario_dir, worktree)
            fixtures.append({"name": name, "directory": str(scenario_dir), "workspace": str(workspace),
                             "original_project": str(original), "plugin": str(plugin),
                             "probe_file": "averages.py", "failure_retry": retry, "git_setup": git})
    manifest = {"schema": "taskplane.claude-prepared-fixtures/v1", "kind": args.prepare_kind,
                "fixtures": fixtures, "candidate": fingerprint(args.plugin_dir)}
    for fixture in fixtures:
        fixture["staged_candidate"] = fingerprint(Path(fixture["plugin"]))
        fixture["probe_sha256"] = digest(read_regular(Path(fixture["workspace"]) / fixture["probe_file"]))
        inputs = [fixture["probe_file"]] if args.prepare_kind == "capabilities" else [
            "averages.py", "settings.py", ".taskplane/bootstrap/scope.json", ".taskplane/bootstrap/tasks.json"]
        fixture["input_sha256"] = {p: digest(read_regular(Path(fixture["workspace"]) / p)) for p in inputs}
        config = load(Path(fixture["directory"]) / "proxy-config.json")
        fixture["delegate_config_sha256"] = digest(json.dumps({k: config[k] for k in ("commands", "probe")}, sort_keys=True).encode())
        fixture["capture_script_sha256"] = digest(read_regular(Path(fixture["directory"]) / "capture.py"))
    save(folder / "prepared.json", manifest)
    report.update(status="prepared", evidence_directory=str(folder), preparation=manifest,
                  prepared_fixture_ref={"path": str(folder / "prepared.json"), "sha256": digest(read_regular(folder / "prepared.json"))},
                  next_action="Independently read/hash each probe on the real host, use installed workspace inspect/bind with those actual references, then rerun the requested mode with --prepared-dir. No host/worker locality is inferred.")


def live_prompt(plugin, workspace, original, failure_retry):
    runtime = shlex.join([str(Path(sys.executable).resolve()), str(plugin / "taskplane/tp.py")])
    selected = shlex.quote(str(workspace))
    retry = """
For B's FIRST prepared attempt only, after successful claim, complete context and
an ordinary Read, run Bash `python3 -c 'raise SystemExit(17)'`. This is deliberate
real command fault injection, not a fabricated hook or terminal event. Write its
actual failure to .taskplane/failure-b.md and return that failure using the host's
native result delivery. Observe its independent host terminal; do NOT accept that task
result. If joined, prepare exactly one FRESH B grant with retry_reason describing
the observed exit17 and removal of the injected failing command. Its worker must
claim/consume context anew, then do the useful settings.py review successfully.
Retain both attempts. A command failure and successful host termination are
different facts. Never mark a process failed merely because the report says so.
If the first attempt remains unknown/live, do not reuse paths or fake recovery:
retain the blocker and stop the retry.
""" if failure_retry else ""
    return f"""Use Taskplane for this explicitly requested bounded standalone Engineering
review in {workspace}. This is a real live integration check: two useful native
workers independently inspect the two supplied Python files, reproduce boundary
defects and return review evidence. Run only this review, never a seven-phase flow.
This request authorizes its two native workers and the bounded fault/retry below;
it does not approve any phase checkpoint. All writes stay in declared report paths.

The actual loaded candidate launcher is: {runtime}
The selected execution workspace is {workspace}. Claude was started in {original}.
Read the installed shared-flow instructions before activation. Execute the exact
activation and start commands below first; setup does not admit arbitrary shell
commands. Then use Bash `cd {selected}` only if pwd differs, so child cwd becomes
the selected worktree. Preserve the parent transcript in its native project location.
Do not write transcript records or call hook entrypoints manually.

Use the loaded CLI and these prepared inputs:
  {runtime} flow activate --workspace {selected} --phase engineering --request-reference live-harness-request
  {runtime} flow start --workspace {selected} --standalone --phase engineering --scope .taskplane/bootstrap/scope.json --tasks .taskplane/bootstrap/tasks.json --request-reference live-harness-request --goal 'Independent review of averages and listener settings'
Inspect the returned run/revision,
fully drain root context, and run an ordinary admitted Read for parent readiness.
The scope and tasks are already prepared; preserve their exact paths and task IDs.

Obtain actual native Agent capacity from the exposed host if available and record
its real reference in prepare's capacity. If this Claude host exposes no capacity,
record host_slots:null, includes_root:false, configured_limit:2, and a reference to
the actual exposed Agent schema that lacks a host limit. Two is this fixture's
explicit admission budget, never an observed host limit. Preserve host launch
refusals and unknown host capacity; do not invent host_slots.
Prepare CW-LIVE-A with flow worker --operation prepare using the current revision.
Launch its exact returned dispatch message with the native Task or Agent tool and
the actual supported background mechanism. Never invent launch arguments; report
unavailable background/concurrent execution if absent. Pass only the focused task, grant, launcher, workspace and
context instruction, not this whole root history. Instruct A to claim, fully drain
all required task context, Read averages.py, then keep its native task active with
one bounded `python3 -c 'import time; time.sleep(60)'` command while
inspecting/reproducing the average([]) boundary.
Use this exact reproduction: `python3 -c 'from averages import average; print(average([]))'`.
The dwell is solely to observe concurrent worker ownership; it is not success
evidence. A must write .taskplane/review-a.md with its actual finding and source
line, then return its final answer normally. If SubagentHandback is actually
exposed, use its exact schema; otherwise rely on the real native completion
notification. Never fabricate a notification or its origin metadata.

Observe A's actual claim, complete context and matching ordinary automatic hook
pair using worker status before preparing B. Use at most six bounded readiness
checks over 45 seconds. Prepare CW-LIVE-B while A remains running, and launch a
distinct native background Agent with its own returned message and grant. B reads
settings.py and reproduces listener_port('70000') violating a valid TCP port range,
using `python3 -c 'from settings import listener_port; print(listener_port("70000"))'`,
then writes .taskplane/review-b.md and returns its final answer through native
result delivery in the same way as A.
{retry}
Each worker must complete normal source reads after context delivery. Neither
worker may run root phase controls, delegate, write sibling reports or call hooks.
If hooks refuse a claim/context because an actual launch record is delayed, allow
at most three fresh calls with the observed reason. Never omit identity or weaken
the checks. A missing SubagentHandback is not evidence of a missing native result:
inspect the actual completion notification and separate stop observation.

Root must wait for actual native results and independent terminal observations.
Read the reports and inspect each current joined attempt. Accept each successful
result with flow worker --operation accept-result, its exact grant and task,
outputs:[the task's review path], checks:[{{name:'Reviewed reproduced source defect',
status:'pass',evidence:the same task review path}}]. Only use pass after actual
review. Do not accept the injected failure or an unknown/live attempt. The CLI,
not report prose, must create accepted task-result records. Preserve all failures.

Write .taskplane/review.md summarizing the actual findings and gaps. Prepare and
submit the normal Engineering packet with actual native lens coverage if all
required evidence permits; present the native dashboard and stop at the pending
human checkpoint. Do not call decide, auto-decide, policy, advance, or finish, and
do not fabricate human messages. If blocked, report the exact blocker and leave
unknown work unknown. The harness supplies normal per-session permissions for the
exact fixture operations; arbitrary commands still require host permission. Use
native Write/Edit for reports and exact CLI commands for workflow operations.
Do not change permissions or install settings. A denied required operation ends
the attempt with its exact blocker; do not repeatedly try denied commands.
"""


def check(name, passed, detail, unknown=False):
    return {"name": name, "status": "pass" if passed else "unknown" if unknown else "fail", "detail": detail}


def response_failed(event):
    response = event.get("tool_response", {})
    return (event.get("is_error") is True or isinstance(response, dict) and
            (response.get("is_error") is True or response.get("exit_code") not in (None, 0)
             or response.get("interrupted") is True))


def admitted(capture):
    if capture.get("delegate_exit_code") != 0:
        return False
    try:
        value = json.loads(capture.get("delegate_stdout", "")) if capture.get("delegate_stdout", "").strip() else {}
    except ValueError:
        return False
    return (value.get("decision") != "block" and value.get("continue") is not False and
            value.get("hookSpecificOutput", {}).get("permissionDecision") != "deny")


def native_completion(stream, session, actor, launch_call):
    """Only structured host events count, never agent-authored report text."""
    return [row for row in stream if actor and launch_call and row.get("type") == "system"
            and row.get("subtype") == "task_notification" and row.get("session_id") == session
            and row.get("task_id") == actor and row.get("tool_use_id") == launch_call
            and row.get("status") == "completed" and isinstance(row.get("summary"), str)
            and row["summary"].strip()]


def candidate_selections(stream, session):
    """Each init is a snapshot; repeated snapshots are not duplicate installs."""
    return [[p for p in row.get("plugins", []) if isinstance(p, dict)
             and str(p.get("name", "")).split("@")[0] == "taskplane"]
            for row in stream if row.get("type") == "system" and row.get("subtype") == "init"
            and row.get("session_id") == session and isinstance(row.get("plugins"), list)]


def overlapping_workers(first, rows):
    """Use actual stop observations, not delayed controller reconciliation."""
    stopped = first.get("stop_observation", {}).get("observed_at")
    return [row for row in rows if row.get("task_id") == "CW-LIVE-B"
            and first.get("claimed_at") and stopped and row.get("claimed_at")
            and row.get("stop_observation", {}).get("observed_at")
            and max(first["claimed_at"], row["claimed_at"])
            < min(stopped, row["stop_observation"]["observed_at"])]


def inspect_live(workspace, original, plugin, captures, native, stream, process, retry):
    """Read corroborating state and host evidence; never repair/mutate it."""
    states, errors = [], []
    for path in (workspace / ".taskplane").glob("workflow-*.json"):
        if path.name.endswith(".initialized.json"):
            continue
        try:
            db = load(path)
            if db.get("root") == process["session_id"]:
                states.extend(db.get("runs", {}).values())
        except (OSError, ValueError) as exc:
            errors.append(str(exc))
    states = [s for s in states if s.get("root") == process["session_id"] and s.get("workspace") == str(workspace)]
    checks = [check("host process completed", process["exit_code"] == 0 and not process["timed_out"], process),
              check("one fresh root workflow", len(states) == 1, {"runs": [s.get("run") for s in states], "errors": errors})]
    state = states[0] if len(states) == 1 else {}
    rows = list(state.get("workers", {}).values())
    results = state.get("task_results", {})
    staged = fingerprint(plugin)
    expected = staged["member_sha256"]
    checks.append(check("automatic candidate hooks", bool(captures) and all(
        c["runtime"]["root"] == str(plugin) and c["runtime_unchanged"] and
        c["runtime"]["member_sha256"] == expected and not c["capability_fixture"] for c in captures),
        {"count": len(captures), "root": str(plugin)}))
    selected = []
    for task_id in ("CW-LIVE-A", "CW-LIVE-B"):
        result = results.get(task_id, {})
        matches = [r for r in rows if r.get("grant_id") == result.get("grant") and r.get("task_id") == task_id]
        row = matches[0] if len(matches) == 1 else {}
        selected.append(row)
        actor = row.get("worker_id")
        events = [c for c in captures if actor and c["input"].get("agent_id") == actor]
        pres = {c["input"].get("tool_use_id"): c for c in events if c["event"] == "PreToolUse"}
        posts = {c["input"].get("tool_use_id"): c for c in events if c["event"] == "PostToolUse"}
        ordinary = [call for call in pres.keys() & posts.keys() if call and
                    pres[call]["input"].get("tool_name") in {"Read", "Bash"} and
                    "flow " not in str(pres[call]["input"].get("tool_input", {})) and
                    admitted(pres[call]) and admitted(posts[call]) and not response_failed(posts[call]["input"])]
        claims, rewrites, completed_context = [], [], []
        for call, before in pres.items():
            cmd = before["input"].get("tool_input", {}).get("command", "")
            if call in posts and admitted(before) and "--operation claim" in cmd and row.get("grant_id", "missing") in cmd:
                try:
                    returned = json.loads(posts[call]["input"].get("tool_response", {}).get("stdout", ""))
                    if returned.get("grant_id") == row.get("grant_id") and returned.get("task_id") == task_id:
                        claims.append(call)
                except (ValueError, TypeError):
                    pass
            if call in posts and "flow context" in cmd and task_id in cmd:
                try:
                    returned = json.loads(posts[call]["input"].get("tool_response", {}).get("stdout", ""))
                    if returned.get("done") is True and returned.get("remaining_required") == 0:
                        completed_context.append(call)
                except (ValueError, TypeError):
                    pass
            try:
                output = json.loads(before["delegate_stdout"])
            except ValueError:
                continue
            rewritten = output.get("hookSpecificOutput", {}).get("updatedInput", {}).get("command", "")
            if "--invocation-ref" in rewritten and call in posts:
                rewrites.append(call)
        handback_calls = [call for call, c in pres.items() if c["input"].get("tool_name") == "SubagentHandback" and admitted(c)]
        stops = [c for c in events if c["event"] == "SubagentStop"]
        handback = row.get("handback", {})
        notifications = native_completion(stream, process["session_id"], actor, row.get("call_id"))
        delivered = handback.get("status") == "delivered" or handback.get("state") == "delivered" or bool(handback.get("delivered_at"))
        receipt = row.get("context_receipt")
        proof = row.get("hook_readiness", {})
        runtime = row.get("expected_runtime", {})
        runtime_match = runtime.get("root") == str(plugin) and bool(runtime.get("member_sha256")) and all(
            expected.get(k) == v and v for k, v in runtime.get("member_sha256", {}).items())
        checks.extend([
            check(task_id + " prepared/claim/context", bool(row.get("prepared_at") and row.get("call_id") and
                  row.get("claimed_at") and receipt and claims and rewrites and completed_context),
                  {"grant": row.get("grant_id"), "worker": actor, "launch_call": row.get("call_id"),
                   "claim_calls": claims, "rewritten_calls": rewrites, "complete_context_calls": completed_context,
                   "context_receipt": receipt}),
            check(task_id + " ordinary automatic hook pair", bool(ordinary and proof.get("matched_call") and runtime_match),
                  {"calls": ordinary, "readiness": proof, "expected_runtime": runtime}),
            check(task_id + " result delivery", bool((handback_calls or notifications) and delivered),
                  {"calls": handback_calls, "notifications": notifications, "controller": handback},
                  unknown=bool((handback_calls or notifications) and not delivered)),
            check(task_id + " independent terminal and root acceptance", bool(stops and row.get("terminal_status") in {"completed", "idle"}
                  and row.get("state") == "accepted" and result.get("accepted_at") and result.get("worker_id") == actor
                  and actor != state.get("root") and not row.get("revoked_at") and not row.get("identity_conflict")),
                  {"terminal": row.get("terminal_status"), "state": row.get("state"), "result": result,
                   "stop_events": [c["input"] for c in stops]}),
        ])
        suffix, source, trigger = ("a", "averages.py", "average") if task_id.endswith("A") else ("b", "settings.py", "port")
        output_path = workspace / f".taskplane/review-{suffix}.md"
        try:
            body = read_regular(output_path, 32768).decode()
            useful = len(body.strip()) >= 100 and source in body and trigger in body.lower()
            manifest = result.get("manifest", {})
            expected_digest = manifest.get(str(output_path.relative_to(workspace)))
            if isinstance(expected_digest, dict):
                expected_digest = expected_digest.get("sha256", expected_digest.get("digest"))
            useful = useful and expected_digest == digest(body.encode())
            detail = {"path": str(output_path), "sha256": digest(body.encode()), "bytes": len(body.encode()),
                      "accepted_fingerprint": expected_digest}
        except (OSError, ValueError, UnicodeError) as exc:
            useful, detail = False, {"error": str(exc)}
        checks.append(check(task_id + " distinct useful scoped output", useful, detail))
    actors = [r.get("worker_id") for r in selected]
    checks.append(check("distinct native workers", all(actors) and len(set(actors)) == 2, actors))
    # Any B attempt overlapping A establishes actual concurrent ownership even
    # when B's first deliberate failing attempt is followed by a fresh retry.
    overlap = overlapping_workers(selected[0], rows)
    checks.append(check("observed concurrent worker lifetimes", bool(overlap), [r["grant_id"] for r in overlap]))
    schema = native["handback_schemas"]
    completion_contract = bool(native.get("completion_notifications")) and all(
        native_completion(stream, process["session_id"], row.get("worker_id"), row.get("call_id"))
        for row in selected)
    supported_delivery = bool(schema) or completion_contract
    checks.append(check("fresh host result delivery contract", supported_delivery,
                        {"handback_schemas": schema, "native_completion": completion_contract},
                        unknown=not supported_delivery))
    selections = candidate_selections(stream, process["session_id"])
    checks.append(check("single candidate plugin selected", bool(selections) and all(
        len(group) == 1 and group[0].get("path") == str(plugin) for group in selections),
        selections, unknown=not selections))
    if workspace != original:
        parent = [s for s in native["sources"] if Path(s["path"]).stem == process["session_id"]]
        initial = [c["input"] for c in captures if c["event"] == "SessionStart"
                   and c["input"].get("session_id") == process["session_id"] and not c["input"].get("agent_id")]
        selected_paths = {c.get("transcript_path") for c in initial if c.get("cwd") == str(original)}
        child_cwds = {c["input"].get("cwd") for c in captures if c["input"].get("agent_id") in actors}
        checks.append(check("worktree execution with original project transcript", bool(parent) and
                            bool(selected_paths) and all(p["path"] in selected_paths for p in parent) and
                            child_cwds == {str(workspace)},
                            {"parent_sources": parent, "initial_root_events": initial,
                             "execution_workspace": str(workspace), "child_cwds": sorted(str(p) for p in child_cwds)}))
    if retry:
        current = selected[1]
        previous = [r for r in rows if r.get("task_id") == "CW-LIVE-B" and r.get("grant_id") != current.get("grant_id")]
        failure_calls = [c for c in captures if c["event"] == "PostToolUse" and response_failed(c["input"])
                         and c["input"].get("agent_id") in {r.get("worker_id") for r in previous}]
        injected = {c["input"].get("tool_use_id") for c in captures if c["event"] == "PreToolUse"
                    and c["input"].get("agent_id") in {r.get("worker_id") for r in previous}
                    and "raise SystemExit(17)" in c["input"].get("tool_input", {}).get("command", "")}
        failure_results = [r for r in native.get("results", []) if r["result"].get("tool_use_id") in injected
                           and r["result"].get("is_error") is True]
        retained = any(r.get("terminal_status") and r.get("state") != "accepted" and r.get("attempt", 0) < current.get("attempt", 0)
                       for r in previous)
        checks.append(check("real failed attempt and fresh bounded retry", bool(retained and (failure_calls or failure_results) and
                            current.get("retry_reason") and len(previous) == 1),
                            {"previous_attempts": previous, "failure_events": [c["input"] for c in failure_calls],
                             "native_failure_results": failure_results,
                             "retry_grant": current.get("grant_id"), "retry_reason": current.get("retry_reason"),
                             "classification": "Real command fault injection; host termination status is reported independently."}))
    return {"status": "pass" if all(c["status"] == "pass" for c in checks) else "fail",
            "checks": checks, "controller_runs": states, "read_errors": errors}


def run_live(args, report):
    if not args.prepared_dir:
        raise ValueError("Run --prepare --prepare-kind live, independently inspect/bind both workspaces, then --live --prepared-dir PATH")
    prepared = load(args.prepared_dir / "prepared.json")
    if prepared.get("kind") != "live":
        raise ValueError("Prepared fixture is not a live fixture")
    if fingerprint(args.plugin_dir) != prepared.get("candidate"):
        raise ValueError("Prepared candidate fingerprint changed; prepare and independently bind a fresh fixture")
    folder = args.prepared_dir
    report.update(evidence_directory=str(folder), scenarios=[],
                  instrumentation={"kind": "unchanged hook command delegation in disposable candidate copy",
                                   "changed_members": ["hooks/hooks.json"], "capability_fixture": False,
                                   "limit": "This verifies the instrumented loaded runtime. Original package hashes are retained separately."})
    # Each scenario starts a new Claude session and a new, isolated workflow.
    for fixture in prepared["fixtures"]:
        name, retry = fixture["name"], fixture["failure_retry"]
        preparation_dir = Path(fixture["directory"])
        scenario_dir = preparation_dir / ("attempt-" + uuid.uuid4().hex)
        scenario_dir.mkdir()
        capture = scenario_dir / "hooks"
        capture.mkdir()
        plugin = Path(fixture["plugin"])
        original, workspace = Path(fixture["original_project"]), Path(fixture["workspace"])
        if not all(p.is_relative_to(folder) for p in (plugin, original, workspace, preparation_dir)):
            raise ValueError("Prepared fixture paths escape their recorded directory")
        if fingerprint(plugin) != fixture.get("staged_candidate"):
            raise ValueError("Prepared staged runtime changed")
        if digest(read_regular(workspace / fixture["probe_file"])) != fixture.get("probe_sha256"):
            raise ValueError("Prepared fixture source probe changed")
        if any(digest(read_regular(workspace / p)) != expected for p, expected in fixture["input_sha256"].items()):
            raise ValueError("Prepared fixture source or task/scope input changed")
        if digest(read_regular(preparation_dir / "capture.py")) != fixture["capture_script_sha256"]:
            raise ValueError("Prepared hook capture script changed")
        if not (workspace / ".taskplane/workspace-binding.json").is_file():
            raise ValueError(f"Prepared workspace needs independent probe/bind before launch: {workspace}")
        for path in (workspace / ".taskplane").glob("workflow-*.json"):
            if path.name.endswith(".initialized.json"):
                continue
            db = load(path)
            if any(r.get("state") in {"prepared", "launch_pending", "bootstrapping", "running", "cancel_requested", "unknown"}
                   for state in db.get("runs", {}).values() for r in state.get("workers", {}).values()):
                raise ValueError("Prepared workspace retains live or unknown worker ownership; reconcile it before any new session")
        config_path = preparation_dir / "proxy-config.json"
        config = load(config_path)
        if digest(json.dumps({k: config[k] for k in ("commands", "probe")}, sort_keys=True).encode()) != fixture["delegate_config_sha256"]:
            raise ValueError("Prepared hook delegate configuration changed")
        config["capture"] = str(capture)
        save(config_path, config)
        git = fixture["git_setup"]
        print(json.dumps({"running": name, "evidence_directory": str(scenario_dir)}), flush=True)
        process = launch(args.claude, plugin, original, scenario_dir,
                         live_prompt(plugin, workspace, original, retry), args.timeout, args.model, workspace)
        captures = [load(p) for p in capture.glob("*.json")]
        stream, errors = stream_rows(scenario_dir / "stream.jsonl")
        native, _ = transcript_evidence(captures, process["session_id"])
        scenario = {"name": name, "process": process, "workspace": str(workspace), "original_project": str(original),
                    "git_setup": git, "staged_candidate": fingerprint(plugin),
                    "observations": capture_summary(captures, native, stream), "native_transcripts": native,
                    "capture_errors": errors,
                    "verification": inspect_live(workspace, original, plugin, captures, native, stream, process, retry)}
        if errors or native["errors"]:
            scenario["verification"]["status"] = "fail"
        report["scenarios"].append(scenario)
        report["status"] = "pass" if len(report["scenarios"]) == 2 and all(
            s["verification"]["status"] == "pass" for s in report["scenarios"]) else "fail"
        save(args.output, report)  # Preserve a completed scenario even if the next one fails.
        if scenario["verification"]["status"] != "pass":
            break  # Resolve the first blocker before spending another host session.
    report["e2e_status"] = report["status"]


if __name__ == "__main__":
    raise SystemExit(main())
